"""Add `is_bank` flag in `Supplier`

Revision ID: 2678787d86e2
Revises: 06e653a729d1
Create Date: 2021-07-28 20:11:51.562380

"""
from alembic import op
import sqlalchemy as sa
from citywok_ms import db
from citywok_ms.supplier.models import Supplier

# revision identifiers, used by Alembic.
revision = "2678787d86e2"
down_revision = "06e653a729d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_bank", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###
    db.session.add(Supplier(name="Bank", is_bank=True))
    db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("supplier", schema=None) as batch_op:
        batch_op.drop_column("is_bank")

    # ### end Alembic commands ###
