"""Add iban to employee

Revision ID: 27c903b94867
Revises: 284daa713702
Create Date: 2021-06-25 14:25:22.636903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c903b94867'
down_revision = '284daa713702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iban', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_employee_iban'), ['iban'])
        batch_op.create_unique_constraint(batch_op.f('uq_employee_nif'), ['nif'])
        batch_op.create_unique_constraint(batch_op.f('uq_employee_niss'), ['niss'])

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_supplier_iban'), ['iban'])
        batch_op.create_unique_constraint(batch_op.f('uq_supplier_nif'), ['nif'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_supplier_nif'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_supplier_iban'), type_='unique')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employee_niss'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_employee_nif'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_employee_iban'), type_='unique')
        batch_op.drop_column('iban')

    # ### end Alembic commands ###
