"""Add accountant_id to employee

Revision ID: 31abbbb774c0
Revises: 27c903b94867
Create Date: 2021-06-28 17:14:34.658410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "31abbbb774c0"
down_revision = "27c903b94867"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employee", schema=None) as batch_op:
        batch_op.add_column(sa.Column("accountant_id", sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(
            batch_op.f("uq_employee_accountant_id"), ["accountant_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employee", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_employee_accountant_id"), type_="unique"
        )
        batch_op.drop_column("accountant_id")

    # ### end Alembic commands ###
