"""Add `income` models

Revision ID: 4e74dbb5fd19
Revises: 2678787d86e2
Create Date: 2021-07-28 21:08:48.617838

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import citywok_ms
from citywok_ms.income.models import INCOME

# revision identifiers, used by Alembic.
revision = "4e74dbb5fd19"
down_revision = "2678787d86e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "income",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "category",
            sqlalchemy_utils.types.choice.ChoiceType(INCOME),
            nullable=False,
        ),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("cash", citywok_ms.utils.models.SqliteDecimal(2), nullable=True),
        sa.Column("check", citywok_ms.utils.models.SqliteDecimal(2), nullable=True),
        sa.Column("card", citywok_ms.utils.models.SqliteDecimal(2), nullable=True),
        sa.Column("transfer", citywok_ms.utils.models.SqliteDecimal(2), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_income")),
    )
    op.create_table(
        "revenue",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "t_revenue", citywok_ms.utils.models.SqliteDecimal(2), nullable=False
        ),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("date", name=op.f("pk_revenue")),
    )
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.add_column(sa.Column("income_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("revenue_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_file_income_id_income"), "income", ["income_id"], ["id"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_file_revenue_id_revenue"),
            "revenue",
            ["revenue_id"],
            ["date"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_file_revenue_id_revenue"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_file_income_id_income"), type_="foreignkey"
        )
        batch_op.drop_column("revenue_id")
        batch_op.drop_column("income_id")

    op.drop_table("revenue")
    op.drop_table("income")
    # ### end Alembic commands ###
