"""`order` module

Revision ID: 58812dfc1d2a
Revises: 31abbbb774c0
Create Date: 2021-07-09 20:17:50.750413

"""
import citywok_ms
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "58812dfc1d2a"
down_revision = "31abbbb774c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_number", sa.String(), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.Column("value", citywok_ms.utils.models.SqliteDecimal(2), nullable=False),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["supplier_id"], ["supplier.id"], name=op.f("fk_order_supplier_id_supplier")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order")),
    )
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_file_order_id_order"), "order", ["order_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("file", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_file_order_id_order"), type_="foreignkey"
        )
        batch_op.drop_column("order_id")

    op.drop_table("order")
    # ### end Alembic commands ###
