"""Initial migration.

Revision ID: 6d50694cef38
Revises: 
Create Date: 2020-07-03 16:56:37.512190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d50694cef38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zh', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'Visiter', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('employee',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('zh_name', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.Enum('M', 'F', name='sex'), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('id_type', sa.Enum('Passport', 'C_Cidadao', 'T_Residencia', 'C_R_Permanente', name='id_type'), nullable=True),
    sa.Column('id_number', sa.String(length=10), nullable=True),
    sa.Column('id_validity', sa.Date(), nullable=True),
    sa.Column('nationality_id', sa.Integer(), nullable=True),
    sa.Column('nif', sa.Integer(), nullable=True),
    sa.Column('niss', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('total_salary', sa.Integer(), nullable=True),
    sa.Column('tax_salary', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_by_id', sa.Integer(), nullable=True),
    sa.Column('update_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['create_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['nationality_id'], ['country.id'], ),
    sa.ForeignKeyConstraint(['update_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nif'),
    sa.UniqueConstraint('niss')
    )
    op.create_table('supplier',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('principal', sa.String(length=50), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('nif', sa.Integer(), nullable=True),
    sa.Column('iban', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('postcode', sa.String(length=15), nullable=True),
    sa.Column('city', sa.String(length=15), nullable=True),
    sa.Column('create_by_id', sa.Integer(), nullable=True),
    sa.Column('update_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['create_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['update_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iban'),
    sa.UniqueConstraint('nif')
    )
    op.create_table('file',
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=30), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('create_by_id', sa.Integer(), nullable=True),
    sa.Column('update_by_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['create_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['update_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('supplier')
    op.drop_table('employee')
    op.drop_table('user')
    op.drop_table('job')
    op.drop_table('country')
    # ### end Alembic commands ###
