"""Add `from_pos` flag to `Expense`

Revision ID: bbab3f826227
Revises: 4e74dbb5fd19
Create Date: 2021-07-28 23:00:05.700533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bbab3f826227"
down_revision = "4e74dbb5fd19"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.add_column(sa.Column("from_pos", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expense", schema=None) as batch_op:
        batch_op.drop_column("from_pos")

    # ### end Alembic commands ###
