"""Add remark to order

Revision ID: fbafa1b42d45
Revises: fcdb7d62ea81
Create Date: 2021-07-07 15:58:31.206501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbafa1b42d45'
down_revision = 'fcdb7d62ea81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remark', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('remark')

    # ### end Alembic commands ###
