"""Associate supplier with order

Revision ID: fcdb7d62ea81
Revises: df067cb57c4a
Create Date: 2021-07-01 18:36:41.839406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fcdb7d62ea81"
down_revision = "df067cb57c4a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "supplier_id",
                sa.Integer(),
                nullable=False,
                server_default="0",
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_order_supplier_id_supplier"),
            "supplier",
            ["supplier_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_order_supplier_id_supplier"), type_="foreignkey"
        )
        batch_op.drop_column("supplier_id")

    # ### end Alembic commands ###
